AWSTemplateFormatVersion: '2010-09-09'
Description: Example Pet Store API written with spring with the aws-serverless-java-container
  library
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Outputs:
  SpringPetStoreApi:
    Description: URL for application
    Export:
      Name: SpringPetStoreApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets
Resources:
  PetStoreFunction:
    Properties:
      CodeUri: s3://hf-lambda-demo/7bab23372602699a97625c5770366220
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: com.hf.testspringboot.StreamLambdaHandler::handleRequest
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java8
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
